$('.p-menu__button').on('click',function(){
    $('.l-contents__right').addClass('is-open');
    $('.l-sidebar__drawer').fadeToggle();
    $('html').css('overflow','hidden');
    }
);
$('.c-menu__btn-close').on('click',function(){
    $('.l-contents__right').removeClass('is-open');
    $('.l-sidebar__drawer').fadeToggle();
    $('html').css('overflow','');
}
);

$('.l-sidebar__drawer').on('click',function(){
    $(this).fadeToggle();
    $('.p-menu__button').removeClass('is-open');
    $('.l-contents__right').removeClass('is-open');
    $('html').css('overflow','');   
    }
);